issues:
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - "gochecknoglobals"
    - "gosec"
    - "gocritic"
    - "wsl"
    - "maligned"
    - "goerr113"
    - "gochecknoinits"
    - "godot"
